-- Create the 'users' table
CREATE TABLE users (
    id       NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name     VARCHAR2(100) NOT NULL,
    bio      VARCHAR2(1024),
    image    VARCHAR2(1024),
    email    VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Create the 'user_followings' table
CREATE TABLE user_followings (
    follower_id NUMBER(19,0) NOT NULL,
    followee_id NUMBER(19,0) NOT NULL,
    CONSTRAINT pk_user_followings PRIMARY KEY (follower_id, followee_id),
    CONSTRAINT fk_follower FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_followee FOREIGN KEY (followee_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Create the 'articles' table
CREATE TABLE articles (
    id          NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    author_id   NUMBER(19,0) NOT NULL,
    title       VARCHAR2(255) NOT NULL,
    slug        VARCHAR2(255) NOT NULL,
    description VARCHAR2(255) NOT NULL,
    body        CLOB NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_articles PRIMARY KEY (id),
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT unique_author_slug UNIQUE (author_id, slug)
);

-- Create the 'tags' table
CREATE TABLE tags (
    id    NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    value VARCHAR2(255) UNIQUE NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

-- Create the 'articles_tags' table
CREATE TABLE articles_tags (
    article_id NUMBER(19,0) NOT NULL,
    tag_id     NUMBER(19,0) NOT NULL,
    CONSTRAINT pk_articles_tags PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_article FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

-- Create the 'article_favorites' table
CREATE TABLE article_favorites (
    article_id NUMBER(19,0) NOT NULL,
    user_id    NUMBER(19,0) NOT NULL,
    CONSTRAINT pk_article_favorites PRIMARY KEY (article_id, user_id),
    CONSTRAINT fk_article_favorited FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Create the 'comments' table
CREATE TABLE comments (
    id          NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    author_id   NUMBER(19,0) NOT NULL,
    article_id  NUMBER(19,0) NOT NULL,
    body        CLOB NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_article FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
);
